pipeline {
    agent any
    tools {
        maven 'MyMaven'
     }
    stages {
        stage('Building Package') {
            steps {
                //def MVN = tool name: 'MyMaven', type: 'maven'
                sh script: 'mvn clean test'
            }
        }
    }
}
